twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        appName: "Lolly Games"
        currency: " CFA"
        codepays: "+33"
        concepteur: "By conception"
        appEmail: "support@rideeasy.fr"
        appPhone: ""
        appAdresse: ""
        bayesite: "https://www.bayeconception.com/"
        bayeemail: "contact@bayeconception.com"
        app_environement: '%env(APP_ENV)%'
        baye: "Baye conception"

when@test:
    twig:
        strict_variables: true
